import type { StyleSpecification } from "@mapmetrics/mapmetrics-gl";

/**
 * Creates the MapAtlas style specification dynamically using the provided API token.
 * No API token is hardcoded here; it is supplied at runtime from environment variables.
 */
export const createMapAtlasStyle = (token: string): StyleSpecification => {
  return {
    version: 8,
    name: "classique",
    metadata: {
      "maputnik:renderer": "mlgljs",
    },
    sources: {
      protomaps: {
        attribution:
          '<a href="https://mapmetrics.org/" target="_blank">MapMetrics</a> © <a href="https://openstreetmap.org" target="_blank">OpenStreetMap</a>',
        type: "vector",
        tiles: [
          `https://gateway.mapmetrics-atlas.net/20250110/{z}/{x}/{y}.mvt?token=${encodeURIComponent(token)}`,
        ],
        maxzoom: 15,
      },
    },
    sprite: "https://cdn.mapmetrics-atlas.net/basemaps-assets/sprites/v4/light",
    glyphs: "https://cdn.mapmetrics-atlas.net/basemaps-assets/fonts/{fontstack}/{range}.pbf",
    layers: [
      {
        id: "background",
        type: "background",
        paint: {
          "background-color": "rgba(200, 189, 174, 1)",
        },
      },
      {
        id: "earth",
        type: "fill",
        source: "protomaps",
        "source-layer": "earth",
        minzoom: 0,
        filter: ["==", "$type", "Polygon"],
        paint: {
          "fill-color": "#F4F1ED",
        },
      },
      {
        id: "landcover",
        type: "fill",
        source: "protomaps",
        "source-layer": "landcover",
        paint: {
          "fill-color": [
            "match",
            ["get", "kind"],
            "grassland",
            "#d2efcf",
            "barren",
            "#fff3d7",
            "urban_area",
            "#e6e6e6",
            "farmland",
            "#d8efd2",
            "glacier",
            "#ffffff",
            "scrub",
            "#eaefd2",
            "#c4e7d2",
          ],
          "fill-opacity": ["interpolate", ["linear"], ["zoom"], 5, 1, 7, 0],
        },
      },
      {
        id: "landuse_park",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: [
          "in",
          "kind",
          "national_park",
          "park",
          "cemetery",
          "protected_area",
          "nature_reserve",
          "forest",
          "golf_course",
          "wood",
          "scrub",
          "grassland",
          "grass",
          "military",
          "naval_base",
          "airfield",
        ],
        paint: {
          "fill-opacity": ["interpolate", ["linear"], ["zoom"], 6, 0, 11, 1],
          "fill-color": [
            "case",
            [
              "in",
              ["get", "kind"],
              [
                "literal",
                [
                  "national_park",
                  "park",
                  "cemetery",
                  "protected_area",
                  "nature_reserve",
                  "forest",
                  "golf_course",
                ],
              ],
            ],
            "#B7EAAC",
            [
              "in",
              ["get", "kind"],
              ["literal", ["wood", "nature_reserve", "forest"]],
            ],
            "#A9DFBF",
            [
              "in",
              ["get", "kind"],
              ["literal", ["scrub", "grassland", "grass"]],
            ],
            "#AED9C4",
            ["in", ["get", "kind"], ["literal", ["glacier"]]],
            "#D0E6F5",
            ["in", ["get", "kind"], ["literal", ["sand"]]],
            "#F2ECE0",
            [
              "in",
              ["get", "kind"],
              ["literal", ["military", "naval_base", "airfield"]],
            ],
            "#CDEACC",
            "#F4F1ED",
          ],
          "fill-translate": {
            stops: [
              [6, [0, 0]],
              [10, [0, 0]],
            ],
          },
        },
      },
      {
        id: "landuse_urban_green",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["in", "kind", "allotments", "village_green", "playground"],
        paint: {
          "fill-color": "#B8E986",
          "fill-opacity": 0.7,
        },
      },
      {
        id: "landuse_hospital",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["==", "kind", "hospital"],
        paint: {
          "fill-color": "#f2d6d6",
        },
      },
      {
        id: "landuse_industrial",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["==", "kind", "industrial"],
        paint: {
          "fill-color": "#E3EDF1",
        },
      },
      {
        id: "landuse_school",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["in", "kind", "school", "university", "college"],
        paint: {
          "fill-color": "#eee1c7",
        },
      },
      {
        id: "landuse_beach",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["in", "kind", "beach"],
        paint: {
          "fill-color": "#FAF3DD",
        },
      },
      {
        id: "landuse_zoo",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["in", "kind", "zoo"],
        paint: {
          "fill-color": "#CDEACC",
        },
      },
      {
        id: "landuse_aerodrome",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["in", "kind", "aerodrome"],
        paint: {
          "fill-color": "#dadbdf",
        },
      },
      {
        id: "roads_runway",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["==", "kind_detail", "runway"],
        paint: {
          "line-color": "#e9e9ed",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            10,
            0,
            12,
            4,
            18,
            30,
          ],
        },
      },
      {
        id: "roads_taxiway",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 13,
        filter: ["==", "kind_detail", "taxiway"],
        paint: {
          "line-color": "#e9e9ed",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            15,
            6,
          ],
        },
      },
      {
        id: "landuse_runway",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["any", ["in", "kind", "runway", "taxiway"]],
        paint: {
          "fill-color": "#e9e9ed",
        },
      },
      {
        id: "water",
        type: "fill",
        source: "protomaps",
        "source-layer": "water",
        filter: ["==", "$type", "Polygon"],
        paint: {
          "fill-color": "#98DCFE",
        },
      },
      {
        id: "water_stream",
        type: "line",
        source: "protomaps",
        "source-layer": "water",
        minzoom: 14,
        filter: ["in", "kind", "stream"],
        paint: {
          "line-color": "#A3D5FF",
          "line-width": 0.5,
        },
      },
      {
        id: "water_river",
        type: "line",
        source: "protomaps",
        "source-layer": "water",
        minzoom: 9,
        filter: ["in", "kind", "river"],
        paint: {
          "line-color": "#A3D5FF",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            9,
            0,
            9.5,
            1,
            18,
            12,
          ],
        },
      },
      {
        id: "landuse_pedestrian",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["==", "kind", "pedestrian"],
        paint: {
          "fill-color": "#f4ebd4",
        },
      },
      {
        id: "landuse_pier",
        type: "fill",
        source: "protomaps",
        "source-layer": "landuse",
        filter: ["==", "kind", "pier"],
        paint: {
          "fill-color": "#D6D6D6",
        },
      },
      {
        id: "roads_tunnels_other_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["all", ["has", "is_tunnel"], ["in", "kind", "other", "path"]],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            14,
            0,
            20,
            7,
          ],
        },
      },
      {
        id: "roads_tunnels_minor_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["has", "is_tunnel"],
          ["==", "kind", "minor_road"],
        ],
        paint: {
          "line-color": "#CBCBCB",
          "line-dasharray": [3, 2],
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            0,
            12.5,
            0.5,
            15,
            2,
            18,
            11,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            12,
            0,
            12.5,
            1,
          ],
        },
      },
      {
        id: "roads_tunnels_link_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["all", ["has", "is_tunnel"], ["has", "is_link"]],
        paint: {
          "line-color": "#D6D6D6",
          "line-dasharray": [3, 2],
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            18,
            11,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            12,
            0,
            12.5,
            1,
          ],
        },
      },
      {
        id: "roads_tunnels_major_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-dasharray": [3, 2],
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            0.5,
            18,
            13,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            9,
            0,
            9.5,
            1,
          ],
        },
      },
      {
        id: "roads_tunnels_highway_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "highway"],
          ["!has", "is_link"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-dasharray": [6, 0.5],
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            3.5,
            0.5,
            18,
            15,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            1,
            20,
            15,
          ],
        },
      },
      {
        id: "roads_tunnels_other",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["all", ["has", "is_tunnel"], ["in", "kind", "other", "path"]],
        paint: {
          "line-color": "#BBBBBB",
          "line-dasharray": [4.5, 0.5],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            14,
            0,
            20,
            7,
          ],
        },
      },
      {
        id: "roads_tunnels_minor",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["has", "is_tunnel"],
          ["==", "kind", "minor_road"],
        ],
        paint: {
          "line-color": "#BBBBBB",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            0,
            12.5,
            0.5,
            15,
            2,
            18,
            11,
          ],
        },
      },
      {
        id: "roads_tunnels_link",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["all", ["has", "is_tunnel"], ["has", "is_link"]],
        paint: {
          "line-color": "#BBBBBB",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            18,
            11,
          ],
        },
      },
      {
        id: "roads_tunnels_major",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["has", "is_tunnel"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#BBBBBB",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            6,
            0,
            12,
            1.6,
            15,
            3,
            18,
            13,
          ],
        },
      },
      {
        id: "roads_tunnels_highway",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["has", "is_tunnel"],
          ["==", ["get", "kind"], "highway"],
          ["!", ["has", "is_link"]],
        ],
        paint: {
          "line-color": "#BBBBBB",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            6,
            1.1,
            12,
            1.6,
            15,
            5,
            18,
            15,
          ],
        },
      },
      {
        id: "buildings",
        type: "fill",
        source: "protomaps",
        "source-layer": "buildings",
        paint: {
          "fill-color": "#ECE6DD",
          "fill-opacity": 0.5,
        },
      },
      {
        id: "roads_pier",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["==", "kind_detail", "pier"],
        paint: {
          "line-color": "#D6D6D6",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            12,
            0,
            12.5,
            0.5,
            20,
            16,
          ],
        },
      },
      {
        id: "roads_minor_service_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 13,
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "minor_road"],
          ["==", "kind_detail", "service"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            18,
            8,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            0.8,
          ],
        },
      },
      {
        id: "roads_minor_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "minor_road"],
          ["!=", "kind_detail", "service"],
        ],
        paint: {
          "line-color": "#F8EECD",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            0,
            12.5,
            0.5,
            15,
            2,
            18,
            11,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            12,
            0,
            12.5,
            1,
          ],
        },
      },
      {
        id: "roads_link_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 13,
        filter: ["has", "is_link"],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            18,
            11,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1.5,
          ],
        },
      },
      {
        id: "roads_major_casing_late",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#b2bcd7",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            6,
            0,
            12,
            1.6,
            15,
            3,
            18,
            13,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            9,
            0,
            9.5,
            1,
          ],
        },
      },
      {
        id: "roads_highway_casing_late",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "highway"],
          ["!has", "is_link"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            3.5,
            0.5,
            18,
            15,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            1,
            20,
            15,
          ],
        },
      },
      {
        id: "roads_other",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["in", "kind", "other", "path"],
          ["!=", "kind_detail", "pier"],
        ],
        paint: {
          "line-color": "#f4e1e1",
          "line-dasharray": [3, 1],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            14,
            0,
            20,
            7,
          ],
        },
      },
      {
        id: "roads_link",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["has", "is_link"],
        paint: {
          "line-color": "#FFF8E1",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            18,
            11,
          ],
        },
      },
      {
        id: "roads_minor_service",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "minor_road"],
          ["==", "kind_detail", "service"],
        ],
        paint: {
          "line-color": "#F0F0F0",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            18,
            8,
          ],
        },
      },
      {
        id: "roads_minor",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "minor_road"],
          ["!=", "kind_detail", "service"],
        ],
        paint: {
          "line-color": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            "#F0F0F0",
            16,
            "#FFF8E1",
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            0,
            12.5,
            0.5,
            15,
            2,
            18,
            11,
          ],
        },
      },
      {
        id: "roads_major_casing_early",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        maxzoom: 12,
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#F8EECD",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            0.5,
            18,
            13,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            9,
            0,
            9.5,
            1,
          ],
        },
      },
      {
        id: "roads_major",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#BEC5D8",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            6,
            0,
            12,
            1.6,
            15,
            3,
            18,
            13,
          ],
        },
      },
      {
        id: "roads_highway_casing_early",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        maxzoom: 12,
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "highway"],
          ["!has", "is_link"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            3.5,
            0.5,
            18,
            15,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            1,
          ],
        },
      },
      {
        id: "roads_highway",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["!has", "is_tunnel"],
          ["!has", "is_bridge"],
          ["==", "kind", "highway"],
          ["!has", "is_link"],
        ],
        paint: {
          "line-color": "#FFF8E1",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            6,
            1.1,
            12,
            1.6,
            15,
            5,
            18,
            15,
          ],
        },
      },
      {
        id: "roads_rail",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: ["==", "kind", "rail"],
        paint: {
          "line-dasharray": [0.3, 0.75],
          "line-opacity": 0.5,
          "line-color": "#B0BEC5",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            6,
            0.15,
            18,
            9,
          ],
        },
      },
      {
        id: "boundaries_country",
        type: "line",
        source: "protomaps",
        "source-layer": "boundaries",
        filter: ["<=", "kind_detail", 2],
        paint: {
          "line-color": "#999999",
          "line-width": 1,
          "line-dasharray": [3, 2],
        },
      },
      {
        id: "boundaries",
        type: "line",
        source: "protomaps",
        "source-layer": "boundaries",
        filter: [">", "kind_detail", 2],
        paint: {
          "line-color": "#999999",
          "line-width": 0.5,
          "line-dasharray": [3, 2],
        },
      },
      {
        id: "roads_bridges_other_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: ["all", ["has", "is_bridge"], ["in", "kind", "other", "path"]],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            14,
            0,
            20,
            7,
          ],
        },
      },
      {
        id: "roads_bridges_link_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: ["all", ["has", "is_bridge"], ["has", "is_link"]],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            18,
            11,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            12,
            0,
            12.5,
            1.5,
          ],
        },
      },
      {
        id: "roads_bridges_minor_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["has", "is_bridge"],
          ["==", "kind", "minor_road"],
        ],
        paint: {
          "line-color": "#CBCBCB",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            0,
            12.5,
            0.5,
            15,
            2,
            18,
            11,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            0.8,
          ],
        },
      },
      {
        id: "roads_bridges_major_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["has", "is_bridge"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            0.5,
            18,
            10,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            9,
            0,
            9.5,
            1.5,
          ],
        },
      },
      {
        id: "roads_bridges_other",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: ["all", ["has", "is_bridge"], ["in", "kind", "other", "path"]],
        paint: {
          "line-color": "#F0F0F0",
          "line-dasharray": [2, 1],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            14,
            0,
            20,
            7,
          ],
        },
      },
      {
        id: "roads_bridges_minor",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["has", "is_bridge"],
          ["==", "kind", "minor_road"],
        ],
        paint: {
          "line-color": "#FFF8E1",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            11,
            0,
            12.5,
            0.5,
            15,
            2,
            18,
            11,
          ],
        },
      },
      {
        id: "roads_bridges_link",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: ["all", ["has", "is_bridge"], ["has", "is_link"]],
        paint: {
          "line-color": "#FFF8E1",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            13,
            0,
            13.5,
            1,
            18,
            11,
          ],
        },
      },
      {
        id: "roads_bridges_major",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["has", "is_bridge"],
          ["==", "kind", "major_road"],
        ],
        paint: {
          "line-color": "#BEC5D8",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            6,
            0,
            12,
            1.6,
            15,
            3,
            18,
            13,
          ],
        },
      },
      {
        id: "roads_bridges_highway_casing",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        minzoom: 12,
        filter: [
          "all",
          ["has", "is_bridge"],
          ["==", "kind", "highway"],
          ["!has", "is_link"],
        ],
        paint: {
          "line-color": "#D6D6D6",
          "line-gap-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            3.5,
            0.5,
            18,
            15,
          ],
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            7,
            0,
            7.5,
            1,
            20,
            15,
          ],
        },
      },
      {
        id: "roads_bridges_highway",
        type: "line",
        source: "protomaps",
        "source-layer": "roads",
        filter: [
          "all",
          ["has", "is_bridge"],
          ["==", "kind", "highway"],
          ["!has", "is_link"],
        ],
        paint: {
          "line-color": "#FFF8E1",
          "line-width": [
            "interpolate",
            ["exponential", 1.6],
            ["zoom"],
            3,
            0,
            6,
            1.1,
            12,
            1.6,
            15,
            5,
            18,
            15,
          ],
        },
      },
      {
        id: "places_subplace",
        type: "symbol",
        source: "protomaps",
        "source-layer": "places",
        filter: ["==", "kind", "neighbourhood"],
        layout: {
          "symbol-sort-key": ["get", "min_zoom"],
          "text-field": ["coalesce", ["get", "name:fr"], ["get", "name:en"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-max-width": 7,
          "text-letter-spacing": 0.1,
          "text-padding": [
            "interpolate",
            ["linear"],
            ["zoom"],
            5,
            2,
            8,
            4,
            12,
            18,
            15,
            20,
          ],
          "text-size": [
            "interpolate",
            ["exponential", 1.2],
            ["zoom"],
            11,
            8,
            14,
            14,
            18,
            24,
          ],
          "text-transform": "uppercase",
        },
        paint: {
          "text-color": "#8f8f8f",
          "text-halo-color": "#D6D6D6",
          "text-halo-width": 1,
          "text-halo-blur": 1,
        },
      },
      {
        id: "places_locality",
        type: "symbol",
        source: "protomaps",
        "source-layer": "places",
        filter: ["==", "kind", "locality"],
        layout: {
          "text-field": ["coalesce", ["get", "name:fr"], ["get", "name:en"], ["get", "name"]],
          "text-font": ["Noto Sans Regular"],
          "text-padding": [
            "interpolate",
            ["linear"],
            ["zoom"],
            5,
            3,
            8,
            7,
            12,
            11,
          ],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            2,
            8,
            4,
            10,
            6,
            11,
            8,
            12,
            10,
            14,
            15,
            16,
          ],
          "text-justify": "auto",
        },
        paint: {
          "text-color": "#5c5c5c",
          "text-halo-color": "#D6D6D6",
          "text-halo-width": 1,
          "text-halo-blur": 1,
        },
      },
      {
        id: "places_country",
        type: "symbol",
        source: "protomaps",
        "source-layer": "places",
        filter: ["==", "kind", "country"],
        layout: {
          "symbol-sort-key": ["get", "min_zoom"],
          "text-field": ["coalesce", ["get", "name:fr"], ["get", "name:en"], ["get", "name"]],
          "text-font": ["Noto Sans Medium"],
          "text-size": [
            "interpolate",
            ["linear"],
            ["zoom"],
            2,
            9,
            6,
            13,
            8,
            16,
          ],
          "text-transform": "uppercase",
        },
        paint: {
          "text-color": "#a3a3a3",
        },
      },
    ],
    id: "atlas_glow",
  } as StyleSpecification;
};
